### Assignment: Write Update Formulas using Derivatives
#### Refer to the definitions and relations given on slides 23, 26, 28, 29 and 31 of the slide deck Linear Regression - An Introduction.PDF. 

In this assignment, you will implement update formulas in form of Python functions. The functions will determine changes in W and b using update formulas and will return the change in W and change in b as a Python tuple. There are two parts of the assignment:

Part 1: Use the loops to implement your function as per definitions given in slide 31. 
Part 2: Use matrix relationship to implement your function as per relations given in slide 28.

The code calls your function using the data defined in this note book. 

The skeleton and most of the code is already provided for you below for this assignment. All that you need to do is to save this file and write code ONLY in the spaces that are surrounded by:

#-- START CODE HERE --# (≈ 3-5 lines of code)

#-- END CODE HERE --#

Do NOT change any other part of this file. You should get identical results as provided in this note book. Make sure there is NO extraneous code. Your file must run out of the box without me doing any tweaks. If your submission does not comply with these requirements, your grades will be impacted. 



In [1]:
# Import NumPy
import numpy as np

In [2]:
import array

#### Define example/experience data (X and Y) and initialize model parameters (W, b, and alpha):
X is a 4 x 3 input matrix (there are 4 inputs and 3 training examples) 

Y is an output row vector (there are 3 ouputs each corresponding to the one training example)

W is the weight row vector with as many weights as there are inputs. These weights will be set up randomly with a predefined seed. 

b is the bias term 

alpha is the learning rate

In [3]:
X = np.array([[1,2,0.5],[2,1,2],[1,2,1],[1,1,2]])
Y = np.array([[1, 0, 1]])
np.random.seed(100)
W = np.random.rand(4).reshape(1,4)
b = 1
alpha = 0.01

#### Let us print shapes of these matrices

In [4]:
print("Shape of X matrix", X.shape)
print("Shape of Y matrix", Y.shape)
print("Shape of W matrix", W.shape)

Shape of X matrix (4, 3)
Shape of Y matrix (1, 3)
Shape of W matrix (1, 4)


### Assignment - Part 1: Write Update Formulas using Derivatives with Loops

In this assignment, you will implement update formulas in form of Python function using loops. The function looks like the following:

def updateModelwithLoops(X, Y, W, b, alpha):
    ....
    return (wchange, bchange)

Here X, Y, W and b are as per definition in the slide 23.

In [20]:
def updateModelwithLoops(X, Y, W, b, alpha):
# Extract n (number of features) and m (number of training examples) from X
    n = X.shape[0]
    m = X.shape[1]
# Define a vector dJdW to store derivatives of the weights in the weight vector W
    dJdb = 0
    dJdW = np.zeros(n).reshape(1, n) 

# Define a vector C to store intermediate Ci's and 
    C = np.zeros(m).reshape(1, m)

# Implement the loops to determine Ci's (Slide 31):
#-- START CODE HERE --# (≈ 3-5 lines of code)
    for i in range(m):
        q = sum(W[0][j] * X[j][i] for j in range(n))
        C[0][i] = -2 * (Y[0][i] - (q + b))
#-- END CODE HERE --#

# Implement the loop to determine dJdb, the derivative of J with respect to b (Slide 31):
#-- START CODE HERE --# (≈ 1-3 lines of code)
    dJdb = sum(C[0][i] for i in range(m))
#-- END CODE HERE --#

# Implement the loop to determine dJdw's, the derivatives of J with respect to w's' (Slide 31):
#-- START CODE HERE --# (≈ 2-5 lines of code)
    for j in range(n):
        dJdW[0][j] = sum(X[j][i] * C[0][i] for i in range(m))
#-- END CODE HERE --#
            
# Write update formula for change in b using derivative determined above (slide 29)
    bchange = - alpha * dJdb

# Write update formula for changes in w's using derivatives determined above (slide 29)
    wchange = np.zeros(n)
    for k in range(n):
        wchange[k] = - alpha * dJdW[0][k] 

# Return in a tuple
    return (wchange, bchange)

In [21]:
# Call the function updateModelwithLoops with example data
updateModelwithLoops(X, Y, W, b, alpha)

(array([-0.23917348, -0.29365775, -0.26859859, -0.246269  ]),
 -0.18741878228027017)

##### You should get the following results:

(array([-0.23917348, -0.29365775, -0.26859859, -0.246269  ]),
 -0.18741878228027017)


### Assignment - Part 2: Write Update Formulas using Derivatives with Linear Algebra

In this assignment, you will implement update formulas in form of Python function using matrix relations. The function looks like the following:

def updateModelwithMatrices(X, Y, W, b, alpha):
    ....
    return (wchange, bchange)

Use relations provided in slide 28.  

In [7]:
def updateModelwithMatrices(X, Y, W, b, alpha):

#-- START CODE HERE --# (≈ 3-5 lines of code)
    k = X.shape[0]
    q = Y - (np.matmul(W, X) + b)   # Y - (WX + B)
    dJdb = -2 * np.matmul(q, np.transpose(np.ones_like(q)))    
    dJdW = np.zeros(k).reshape(1, k)
    dJdW[0] = array.array('f', (-2 * np.matmul(q, np.transpose(X[i])) for i in range(k)))
#-- END CODE HERE --#

    bchange = - alpha * dJdb
    wchange = - alpha * dJdW 
    return (wchange, bchange)

In [8]:
# Call the function updateweightsMatrices with example data
updateModelwithMatrices(X, Y, W, b, alpha)

(array([[-0.23917349, -0.29365776, -0.26859859, -0.246269  ]]),
 array([[-0.18741878]]))

##### You should get the following results:

(array([[-0.23917348, -0.29365775, -0.26859859, -0.246269  ]]),
 array([[-0.18741878]]))