In [11]:
import numpy as np

# Get W2 and B2 on Train Data 

In [13]:
# Get the training data
data_train = np.loadtxt('iristrain-1.csv', delimiter=',', skiprows=1)
X_Train, Y_Train = np.array(data_train[:, 0:4]), np.array(data_train[:, 4])

X_Train = np.transpose(X_Train)
Y_Train = np.transpose(Y_Train)

print(X_Train.shape)
print(Y_Train.shape)

(4, 80)
(80,)


In [16]:
# number of training examples
m = 80

# number of features
n = 4

W0 = np.eye(n)
W1 = W0
B0 = 0
B1 = 0
W2 = np.ones((1, n))
B2 = 1

print("W0: \n", W0)
print("W1: \n", W1)
print("W2: \n", W2)
print("B0: \n", B0)
print("B1: \n", B1)
print("B2: \n", B2)

W0: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
W1: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
W2: 
 [[1. 1. 1. 1.]]
B0: 
 0
B1: 
 0
B2: 
 1


In [6]:
def identity_act(yhat):
    return yhat

def tanh_act(yhat):
    return (np.exp(yhat) - np.exp(-yhat)) / (np.exp(yhat) + np.exp(-yhat))

def sigmoid(yhat):
    return 1 / (1 + np.exp(-yhat))

In [33]:
# X = training data read from the file
# for h in range(g):
#   X0 = X         # Assign input vector to the input of Layer 0 (unit activation)       
#   G0 = W0 X0 + B0 # Determine G0   
#   H0 = f0(G0)    # Apply activation function of Layer 0
#   X1 = H0
#   G1 = W1 X1 + B1 # Determine G1   
#   H1 = f1(G1)    # Apply activation function of Layer 1 (unit activation)
#   X2 = H1
#   G2 = W2 X2 + B2 # Determine G2   
#   H2 = f2(G2)    # Apply activation function of Layer 2 (sigmoid activation)

#  J[0,h] = ...... # Determine cost function
#  # Determine derivatives using the code from past Logistic Regression assignment
#  # Use update formula to update W2 and B2
#  # Loop
# print(W2 and B2) 

alpha = 0.05
g = 100000
J = np.zeros(g).reshape(1,g)

for h in range(g):
    X0 = X_Train
    G0 = np.matmul(W0, X0)
    H0 = identity_act(G0) # Layer 0 Activation
    X1 = H0

    G1 = np.matmul(W1,X1) + B1
    H1 = identity_act(G1) # Layer 1 Activation
    X2 = H1

    G2 = np.matmul(W2,X2) + B2
    H2 = sigmoid(G2) # Layer 2 Activation

    Y_hat = H2
    J[0, h] = -1 / m * (np.matmul(np.transpose(Y_Train),
                                  np.transpose(np.log(Y_hat))) + np.matmul(np.transpose(
        (1 - Y_Train)), np.transpose(np.log(1 - Y_hat))))
    dJdz = Y_hat - Y_Train
    dJdb = np.sum(dJdz) / m
    dJdw = 1/m*np.matmul(dJdz, np.transpose(X_Train))
    W2 = W2 - (alpha * dJdw)
    B2 = B2 - (alpha * dJdb)
#     W1 = W1 - (alpha*dJdw)
#     B1 = B1 - (alpha*dJdb)


# print(dJdw)
# print(Y_hat.shape)
# print(W2.shape)
# print(J)
#     J[0,h] = -1/m*np.sum(Y_Train[h]*np.log(Y_hat)+(1-Y_Train[h])*np.log(1-Y_hat))
#     dJdz = Y_hat - Y_Train[h]
#     dJdb = np.sum(dJdz)/m
#     dJdw = 1/m*np.matmul(dJdz, X_Train)

print("W2: \n", W2)
print("B2: \n", B2)

W2: 
 [[-1.37203655 -3.55865762  5.82179189  3.3445902 ]]
B2: 
 0.08939373624452765


# Get W2 and B2 on Test Data

In [7]:
data_test = np.loadtxt('iristest-1.csv', delimiter=',', skiprows=1)
X_Test, Y_Test = np.array(data_train[:, 0:4]), np.array(data_train[:, 4])
X_Test, Y_Test = np.transpose(X_Test), np.transpose(Y_Test)

In [35]:
# number of training examples
m = 20

# number of features
n = 4

W0 = np.eye(n)
W1 = W0
B0 = 0
B1 = 0
W2 = np.ones((1, n))
B2 = 1

print("W0: \n", W0)
print("W1: \n", W1)
print("W2: \n", W2)
print("B0: \n", B0)
print("B1: \n", B1)
print("B2: \n", B2)

W0: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
W1: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
W2: 
 [[1. 1. 1. 1.]]
B0: 
 0
B1: 
 0
B2: 
 1


In [10]:
# X = training data read from the file
# for h in range(g):
#   X0 = X         # Assign input vector to the input of Layer 0 (unit activation)       
#   G0 = W0 X0 + B0 # Determine G0   
#   H0 = f0(G0)    # Apply activation function of Layer 0
#   X1 = H0
#   G1 = W1 X1 + B1 # Determine G1   
#   H1 = f1(G1)    # Apply activation function of Layer 1 (unit activation)
#   X2 = H1
#   G2 = W2 X2 + B2 # Determine G2   
#   H2 = f2(G2)    # Apply activation function of Layer 2 (sigmoid activation)

#  J[0,h] = ...... # Determine cost function
#  # Determine derivatives using the code from past Logistic Regression assignment
#  # Use update formula to update W2 and B2
#  # Loop
# print(W2 and B2) 

alpha = 0.05
g = 100000
J = np.zeros(g).reshape(1, g)

for h in range(g):
    X0 = X_Test
    G0 = np.matmul(W0, X0) + B0
    H0 = identity_act(G0) # Layer 0 Activation
    X1 = H0

    G1 = np.matmul(W1, X1) + B1
    H1 = identity_act(G1) # Layer 1 Activation
    X2 = H1

    G2 = np.matmul(W2, X2) + B2
    H2 = sigmoid(G2) # Layer 2 Activation

    Y_hat = H2
    J[0,h] = -1 / m * (np.matmul(np.transpose(Y_Test), np.transpose(np.log(Y_hat)))
                    + np.matmul(np.transpose(
                        (1 - Y_Test)), np.transpose(np.log(1 - Y_hat))))
    dJdz = Y_hat - Y_Train
    dJdb = np.sum(dJdz) / m
    dJdw = 1 / m * np.matmul(dJdz, np.transpose(X_Test))
    W2 = W2 - (alpha * dJdw)
    B2 = B2 - (alpha * dJdb)

print("W2: \n", W2)
print("B2: \n", B2)

W2: 
 [[-1.54238344 -4.09501682  6.71390778  3.80441623]]
B2: 
 -0.016293016705795173
