In [2]:
import numpy as np

In [3]:
data_train = np.loadtxt('iristrain-1.csv', delimiter=',', skiprows=1)
X_Train = data_train[:,0:4]
Y_Train = data_train[:, 4]

# X_Train = np.transpose(X_Train)
# Y_Train = np.transpose(Y_Train)

print(X_Train.shape)
print(Y_Train.shape)

(80, 4)
(80,)


In [23]:
# number of training examples
m = 80

# number of features
n = 4

# initialize parameters
W0 = np.ones((n,n))
B0 = 0
W1 = np.ones((3,n))*0.5
W2 = np.ones((1,n-1))*0.5
B1 = 0.5
B2 = B1

print("W0: \n", W0)
print("W1: \n", W1)
print("W2: \n", W2)
print(X_Train.shape)

W0: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
W1: 
 [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
W2: 
 [[0.5 0.5 0.5]]
(80, 4)


In [36]:
def identity_act(yhat):
    return yhat

def tanh_act(yhat):
    return (np.exp(yhat)-np.exp(-yhat))/(np.exp(yhat)+np.exp(-yhat))

def sigmoid(yhat):
    return 1/(1+np.exp(-yhat))


def cost_func(W0,W1,W2,B0,B1,B2,X,Y):
    #layer 1
    H0 =  identity_act(np.matmul(W0,np.transpose(X))+B0)
    X1 = H0
    
    #layer 2
    H1 = tanh_act(np.matmul(W1,X1)+B1)
    X2 = H1
    
    # layer 3
    H2 = sigmoid(np.matmul(W2,X2)+B2)
    Y_hat = np.transpose(H2)
    
    # Our matrix representation of the cost function
    
    print("Matrix Representation of Cost Function : -1/m*(np.matmul(Y,np.log(Y_hat))+np.matmul((1-Y),np.log(1-Y_hat)))")
    return -1/m*(np.matmul(Y,np.log(Y_hat))+np.matmul((1-Y),np.log(1-Y_hat)))

print("Cost (Train): ", float(cost_func(W0,W1,W2,B0,B1,B2, X_Train, Y_Train)))

Matrix Representation of Cost Function : -1/m*(np.matmul(Y,np.log(Y_hat))+np.matmul((1-Y),np.log(1-Y_hat)))
Cost (Train):  1.126928011042972


In [37]:
data_test = np.loadtxt('iristest-1.csv', delimiter=',', skiprows=1)
X_Test = data_test[:,0:4]
Y_Test = data_test[:, 4]

# X_Train = np.transpose(X_Train)
# Y_Train = np.transpose(Y_Train)

print(X_Test.shape)
print(Y_Test.shape)

(20, 4)
(20,)


In [38]:
# initialize parameters
W0 = np.ones((n,n))
B0 = 0
W1 = np.ones((3,n))*0.5
W2 = np.ones((1,n-1))*0.5
B1 = 0.5
B2 = B1

In [39]:
print("Cost (Test): ", float(cost_func(W0,W1,W2,B0,B1,B2, X_Test, Y_Test)))

Matrix Representation of Cost Function : -1/m*(np.matmul(Y,np.log(Y_hat))+np.matmul((1-Y),np.log(1-Y_hat)))
Cost (Test):  0.281732002760743
