In [14]:
import numpy as np

In [15]:
def activation(yhat):
    return 1 / (1 + np.exp(-yhat))

def loss(y, yhat):
    return -((1 - y) * np.log(1-yhat) + y * np.log(yhat))

In [16]:
trainingData = np.loadtxt('iristrain-1.csv', delimiter=',', skiprows=1)
X_train = trainingData[:, 0:4]
Y_train = trainingData[:, 4]

# training examples
m = X_train.shape[0]

# number of features
n = X_train.shape[1]

In [24]:
print("X=\n", X_train)
print("\nY=\n", Y_train)

X=
 [[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.3]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [5.6 3.

In [19]:
#Iterations
h = 100000
alpha = 0.05

# # Model Parameters
# b = 1
# W = np.zeros(n).reshape(1, n)
 
# # Initialization of J and Yhat
# J = np.zeros(h).reshape(1, h)
# Yhat = np.zeros(m).reshape(1, m)

In [41]:
def logisticRegression(h, alpha, X, Y):
    # training examples
    m = X.shape[0]
    
    # number of features
    n = X.shape[1]
    
    # Model Parameters
    b = 1
    W = np.zeros(n).reshape(1, n)
    
    # Initialization of J and Yhat
    J = np.zeros(h).reshape(1, h)
    Yhat = np.zeros(m).reshape(1, m)
    
    for g in range(h):
        Yhat = activation(np.matmul(W, np.transpose(X) + b))
        J[0, g] = -1 / m * np.sum(Y * np.log(Yhat) + (1 - Y) * np.log(1 - Yhat))
        dJdz = Yhat - Y
        dJdb = np.sum(dJdz) / m
        dJdw = 1 / m * np.matmul(dJdz, X)
        b -= alpha * dJdb
        W -= alpha * dJdw
    
    return (b, W, J)

In [43]:
(b, w, J) = logisticRegression(h, alpha, X_train, Y_train)
print("Jcost = {}".format(J[0,h-1]))
print("b = {}".format(b))
print("W = ", W)

Jcost = 0.00023645227980541233
b = 0.2331343307740748
W =  [[0. 0. 0. 0.]]
