In [149]:
import numpy as np

Read the data and split into traning and testing

In [150]:
data = np.loadtxt('pattern_rand.csv', delimiter=',', skiprows=1)

train_split = 320

# Train data
X_train = np.transpose(np.asarray(data[0:train_split,0:2]))
Y_train = np.transpose(np.asarray(data[0:train_split,2]))

# Test data
X_test = np.asarray(data[train_split:,0:2])
Y_test = np.asarray(data[train_split:,2])

array([[-6.89650077e-01,  5.60516710e-02],
       [-1.74047644e+00, -3.35417091e+00],
       [ 1.95434163e+00,  3.29303507e+00],
       [ 1.46542426e+00, -3.74752122e+00],
       [-1.04639064e+00, -3.49157180e-02],
       [-3.67848584e+00, -1.08907784e+00],
       [-2.94271312e+00,  5.98400278e-01],
       [-1.04781874e-01,  1.32949014e+00],
       [ 3.64164557e+00,  1.62266735e+00],
       [ 1.01581264e+00,  5.22121460e-02],
       [-3.54248914e+00,  1.78963702e+00],
       [ 2.35054158e+00,  2.72939371e-01],
       [-2.17037528e+00, -1.53233098e+00],
       [-1.42903599e+00,  3.36516611e+00],
       [-1.32788242e+00,  1.87397374e+00],
       [ 2.14392814e+00,  1.50947448e+00],
       [ 5.97232251e-01, -2.78639552e+00],
       [ 1.47956051e+00,  2.19677132e+00],
       [-1.23945887e+00, -1.71623636e+00],
       [-3.43576640e-02,  2.87708911e-01],
       [ 3.50798767e+00,  1.70719390e+00],
       [-2.42617257e+00, -1.46911175e+00],
       [ 4.33926911e-01, -2.50361458e+00],
       [ 6.

Define our initial layer weights and biases

In [151]:
n = 2 # number of features
m = train_split # number of samples

W0 = np.eye(n)
W1 = np.asarray([[1, 0] , [0, 1], [0, 0], [0, 0]]).reshape(4,2)
W2 = np.ones((1,4))
B0 = 0
B1 = 0
B2 = 1

print("W0: \n", W0)
print("W1: \n", W1)
print("W2: \n", W2)

W0: 
 [[1. 0.]
 [0. 1.]]
W1: 
 [[1 0]
 [0 1]
 [0 0]
 [0 0]]
W2: 
 [[1. 1. 1. 1.]]


Create our activation functions to be used

In [152]:
def identity_act(yhat):
    return yhat

def tanh_act(yhat):
    return (np.exp(yhat)-np.exp(-yhat))/(np.exp(yhat)+np.exp(-yhat))

def sigmoid(yhat):
    return 1/(1+np.exp(-yhat))

Train over 100,000 iterations to obtain our W2 and B2

In [153]:
# X = training data read from the file
# for h in range(g):
#   X0 = X         # Assign input vector to the input of Layer 0 (unit activation)       
#   G0 = W0 X0 + B0 # Determine G0   
#   H0 = f0(G0)    # Apply activation function of Layer 0
#   X1 = H0
#   G1 = W1 X1 + B1 # Determine G1   
#   H1 = f1(G1)    # Apply activation function of Layer 1 (unit activation)
#   X2 = H1
#   G2 = W2 X2 + B2 # Determine G2   
#   H2 = f2(G2)    # Apply activation function of Layer 2 (sigmoid activation)

#  J[0,h] = ...... # Determine cost function
#  # Determine derivatives using the code from past Logistic Regression assignment
#  # Use update formula to update W2 and B2
#  # Loop
# print(W2 and B2) 


alpha = 0.05
g = 100000
J = np.zeros(g).reshape(1,g)
for h in range(g):
    X0 = X_train
    G0 = np.matmul(W0,X0)
    H0 = identity_act(G0) # Layer 0 Activation
    X1 = H0

    G1 = np.matmul(W1,X1) + B1
    H1 = identity_act(G1) # Layer 1 Activation
    X2 = H1


    G2 = np.matmul(W2,X2) + B2
    H2 = sigmoid(G2) # Layer 2 Activation

    Y_hat = H2
    J[0,1] = -1/m*(np.matmul(np.transpose(Y_train),np.transpose(np.log(Y_hat)))+np.matmul(np.transpose((1-Y_train)),np.transpose(np.log(1-Y_hat))))
    dJdz = Y_hat - Y_train
    dJdb = np.sum(dJdz)/m
    dJdw = 1/m*np.matmul(dJdz, np.transpose(X_train))
    W2[:,0:2] = W2[:,0:2] - (alpha*dJdw)
    B2 = B2 - (alpha*dJdb)
    
print("W2: \n", W2)
print("B2: \n", B2)

W2: 
 [[ 0.10787189 -0.21458466  1.          1.        ]]
B2: 
 0.0294891943765066


With our W2 and B2, create our validation set to compare to the real results

In [154]:
Y_val = []
for i in range(len(Y_test)):
    res = W2[0,0]*X_test[i,0]+W2[0,1]*X_test[i,1]
    result = sigmoid(res+B2)
    if (result > 0.5):
        Y_val.append(1)
    else:
        Y_val.append(0)
print("Y_Val:", Y_val)
print("Y_Test:", Y_test)

Y_Val: [0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1]
Y_Test: [1. 1. 0. 1. 0. 0. 1. 0. 1. 1. 1. 1. 0. 0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 1.
 0. 1. 0. 1

Compute the error between the validation set and test 

In [ ]:
errors = 0
for i in range(len(Y_val)):
    if (Y_val[i] != Y_test[i]):
        errors +=1
        
percentage_acc = (len(Y_val) - errors) / len(Y_val) * 100
print("The Percentage Accuracy is ", percentage_acc, "%")